# SQL Aggregations, Filtering & Subqueries
**Date:** 2026-06-26
**Tool:** PostgreSQL (QueryLab)
**Database:** flipkart_db | **Table:** products

This notebook documents all SQL queries practiced on Day 16, organized by concept with observations.

## Table Schema

| Column         | Type          | Constraints                        |
|----------------|---------------|------------------------------------|
| product_id     | serial        | PRIMARY KEY                        |
| name           | varchar(100)  | NOT NULL                           |
| sku_code       | char(8)       | UNIQUE, NOT NULL, length must be 8 |
| price          | numeric(10,2) | DEFAULT 0, CHECK >= 0              |
| stock_quantity | int           | DEFAULT 0, CHECK >= 0              |
| is_available   | boolean       | DEFAULT TRUE                       |
| category       | text          | NOT NULL                           |
| added_on       | date          | DEFAULT current_date               |
| last_update    | timestamp     | DEFAULT now()                      |

## Dataset — 10 Products Inserted

| product_id | name              | sku_code | price   | stock | category       |
|------------|-------------------|----------|---------|-------|----------------|
| 1          | Wireless Mouse    | WM123456 | 699.99  | 50    | Electronics    |
| 2          | Bluetooth Speaker | BS234567 | 1499.00 | 30    | Electronics    |
| 3          | Laptop Stand      | LS345678 | 799.50  | 20    | Accessories    |
| 4          | USB-C Hub         | UC456789 | 1299.99 | 15    | Accessories    |
| 5          | Notebook          | NB567890 | 99.99   | 100   | Stationery     |
| 6          | Pen Set           | PS678901 | 199.00  | 200   | Stationery     |
| 7          | Coffee Mug        | CM789012 | 299.00  | 75    | Home & Kitchen |
| 8          | LED Desk Lamp     | DL890123 | 899.00  | 40    | Home & Kitchen |
| 9          | Yoga Mat          | YM901234 | 499.00  | 25    | Fitness        |
| 10         | Water Bottle      | WB012345 | 349.00  | 60    | Fitness        |

In [1]:
from sqlalchemy import create_engine
import pandas as pd

In [2]:
engine = create_engine("postgresql+psycopg2://himanshumahakud@localhost:5432/flipkart_db")

In [3]:
engine = create_engine("postgresql+psycopg2://himanshumahakud:4146@localhost:5432/flipkart_db")

## 1. Basic SELECT & Filtering

In [4]:
query = """
SELECT *
FROM products;
"""

df = pd.read_sql(query, engine)

df

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,2,Bluetooth Speaker,BS234567,1499.00,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
2,3,Laptop Stand,LS345678,799.50,20,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
3,4,USB-C Hub,UC456789,1299.99,15,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
4,5,Notebook,NB567890,99.99,100,True,Stationery,2026-06-26,2026-06-26 11:27:40.806345
5,6,Pen Set,PS678901,199.00,200,False,Stationery,2026-06-26,2026-06-26 11:27:40.806345
6,7,Coffee Mug,CM789012,299.00,75,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
7,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
8,9,Yoga Mat,YM901234,499.00,25,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345
9,10,Water Bottle,WB012345,349.00,60,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345

In [7]:
query = """
SELECT
    name,
    price
FROM products;
"""

pd.read_sql(query, engine)

                name    price
0     Wireless Mouse   699.99
1  Bluetooth Speaker  1499.00
2       Laptop Stand   799.50
3          USB-C Hub  1299.99
4           Notebook    99.99
5            Pen Set   199.00
6         Coffee Mug   299.00
7      LED Desk Lamp   899.00
8           Yoga Mat   499.00
9       Water Bottle   349.00

In [8]:
query = """
SELECT *
FROM products
WHERE category = 'Electronics';
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,2,Bluetooth Speaker,BS234567,1499.00,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345

In [9]:
query = """
SELECT *
FROM products
WHERE price > 500;
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,2,Bluetooth Speaker,BS234567,1499.00,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
2,3,Laptop Stand,LS345678,799.50,20,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
3,4,USB-C Hub,UC456789,1299.99,15,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
4,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345

In [10]:
query = """
SELECT *
FROM products
WHERE price > 1000
AND category = 'Electronics';
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,2,Bluetooth Speaker,BS234567,1499.0,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345

In [11]:
query = """
SELECT *
FROM products
WHERE price BETWEEN 400 AND 1000;
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,3,Laptop Stand,LS345678,799.50,20,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
2,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
3,9,Yoga Mat,YM901234,499.00,25,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345

In [12]:
query = """
SELECT *
FROM products
WHERE category IN
('Electronics',
 'Home & Kitchen',
 'Fitness');
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,2,Bluetooth Speaker,BS234567,1499.00,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
2,7,Coffee Mug,CM789012,299.00,75,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
3,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
4,9,Yoga Mat,YM901234,499.00,25,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345
5,10,Water Bottle,WB012345,349.00,60,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345

In [13]:
query = """
SELECT *
FROM products
WHERE NOT category = 'Electronics';
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,3,Laptop Stand,LS345678,799.50,20,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
1,4,USB-C Hub,UC456789,1299.99,15,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
2,5,Notebook,NB567890,99.99,100,True,Stationery,2026-06-26,2026-06-26 11:27:40.806345
3,6,Pen Set,PS678901,199.00,200,False,Stationery,2026-06-26,2026-06-26 11:27:40.806345
4,7,Coffee Mug,CM789012,299.00,75,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
5,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
6,9,Yoga Mat,YM901234,499.00,25,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345
7,10,Water Bottle,WB012345,349.00,60,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345

In [14]:
import pandas as pd

query = """
SELECT *
FROM products;
"""

result = pd.read_sql(query, engine)
result

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,2,Bluetooth Speaker,BS234567,1499.00,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
2,3,Laptop Stand,LS345678,799.50,20,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
3,4,USB-C Hub,UC456789,1299.99,15,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
4,5,Notebook,NB567890,99.99,100,True,Stationery,2026-06-26,2026-06-26 11:27:40.806345
5,6,Pen Set,PS678901,199.00,200,False,Stationery,2026-06-26,2026-06-26 11:27:40.806345
6,7,Coffee Mug,CM789012,299.00,75,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
7,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345
8,9,Yoga Mat,YM901234,499.00,25,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345
9,10,Water Bottle,WB012345,349.00,60,True,Fitness,2026-06-26,2026-06-26 11:27:40.806345

In [15]:
query = """
SELECT name, price
FROM products;
"""

pd.read_sql(query, engine)

                name    price
0     Wireless Mouse   699.99
1  Bluetooth Speaker  1499.00
2       Laptop Stand   799.50
3          USB-C Hub  1299.99
4           Notebook    99.99
5            Pen Set   199.00
6         Coffee Mug   299.00
7      LED Desk Lamp   899.00
8           Yoga Mat   499.00
9       Water Bottle   349.00

In [16]:
query = """
SELECT *
FROM products
WHERE price > 500;
"""

pd.read_sql(query, engine)

,product_id,name,sku_code,price,stock_quantity,is_available,category,added_on,last_update
0,1,Wireless Mouse,WM123456,699.99,50,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
1,2,Bluetooth Speaker,BS234567,1499.00,30,True,Electronics,2026-06-26,2026-06-26 11:27:40.806345
2,3,Laptop Stand,LS345678,799.50,20,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
3,4,USB-C Hub,UC456789,1299.99,15,True,Accessories,2026-06-26,2026-06-26 11:27:40.806345
4,8,LED Desk Lamp,DL890123,899.00,40,True,Home & Kitchen,2026-06-26,2026-06-26 11:27:40.806345