In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("../datasets/student_performance.csv")

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.shape

(24, 10)

In [17]:
df.head()

,Student_ID,Age,Study_Hours,Attendance_Percent,Assignments_Completed,Quiz_Score,Midterm_Score,Final_Score,Projects_Completed,Overall_Percentage
0,1,18,2,78,8,65,68,70,1,68
1,2,19,3,82,9,70,72,74,2,72
2,3,20,4,85,10,75,78,80,2,78
3,4,18,1,70,6,60,62,65,1,63
4,5,21,5,90,10,82,85,88,3,85

In [19]:
df

,Student_ID,Age,Study_Hours,Attendance_Percent,Assignments_Completed,Quiz_Score,Midterm_Score,Final_Score,Projects_Completed,Overall_Percentage
0,1,18,2,78,8,65,68,70,1,68
1,2,19,3,82,9,70,72,74,2,72
2,3,20,4,85,10,75,78,80,2,78
3,4,18,1,70,6,60,62,65,1,63
4,5,21,5,90,10,82,85,88,3,85
5,6,19,2,76,7,64,67,69,1,67
6,7,20,4,88,9,78,80,83,2,80
7,8,22,6,95,10,88,90,92,3,90
8,9,18,3,80,8,69,71,73,2,71
9,10,21,5,91,10,84,86,89,3,87
10,11,19,2,77,7,66,68,71,1,69
11,12,20,4,86,9,76,79,81,2,79
12,13,18,1,72,6,58,61,63,1,61
13,14,22,6,96,10,90,92,94,3,92
14,15,21,5,89,10,83,85,87,3,85
15,16,19,3,81,8,71,73,75,2,73
16,17,20,4,84,9,74,77,79,2,77
17,18,18,2,75,7,63,65,67,1,65
18,19,22,6,94,10,89,91,93,3,91
19,20,21,5,92,10,85,87,90,3,88
20,21,19,3,79,8,68,70,72,2,70
21,22,20,4,87,9,77,80,82,2,80
22,23,18,2,74,7,62,64,66,1,64
23,24,22,6,97,10,91,93,95,3,93

In [20]:
df["Final_Score"].mean()

np.float64(79.08333333333333)

In [21]:
df["Final_Score"].var()

103.38405797101449

In [22]:
df.columns

Index(['Student_ID', 'Age', 'Study_Hours', 'Attendance_Percent',
       'Assignments_Completed', 'Quiz_Score', 'Midterm_Score', 'Final_Score',
       'Projects_Completed', 'Overall_Percentage'],
      dtype='object')

In [23]:
df.loc[:, 'Age']

0     18
1     19
2     20
3     18
4     21
5     19
6     20
7     22
8     18
9     21
10    19
11    20
12    18
13    22
14    21
15    19
16    20
17    18
18    22
19    21
20    19
21    20
22    18
23    22
Name: Age, dtype: int64

In [24]:
df.loc[:, ['Age', 'Study_Hours', 'Attendance_Percent']]

    Age  Study_Hours  Attendance_Percent
0    18            2                  78
1    19            3                  82
2    20            4                  85
3    18            1                  70
4    21            5                  90
5    19            2                  76
6    20            4                  88
7    22            6                  95
8    18            3                  80
9    21            5                  91
10   19            2                  77
11   20            4                  86
12   18            1                  72
13   22            6                  96
14   21            5                  89
15   19            3                  81
16   20            4                  84
17   18            2                  75
18   22            6                  94
19   21            5                  92
20   19            3                  79
21   20            4                  87
22   18            2                  74
23   22            6                  97

In [25]:
df.loc[:8, ['Age', 'Study_Hours', 'Attendance_Percent']]

   Age  Study_Hours  Attendance_Percent
0   18            2                  78
1   19            3                  82
2   20            4                  85
3   18            1                  70
4   21            5                  90
5   19            2                  76
6   20            4                  88
7   22            6                  95
8   18            3                  80

In [26]:
df.loc[9:16]

,Student_ID,Age,Study_Hours,Attendance_Percent,Assignments_Completed,Quiz_Score,Midterm_Score,Final_Score,Projects_Completed,Overall_Percentage
9,10,21,5,91,10,84,86,89,3,87
10,11,19,2,77,7,66,68,71,1,69
11,12,20,4,86,9,76,79,81,2,79
12,13,18,1,72,6,58,61,63,1,61
13,14,22,6,96,10,90,92,94,3,92
14,15,21,5,89,10,83,85,87,3,85
15,16,19,3,81,8,71,73,75,2,73
16,17,20,4,84,9,74,77,79,2,77

In [27]:
df.iloc[:4]

,Student_ID,Age,Study_Hours,Attendance_Percent,Assignments_Completed,Quiz_Score,Midterm_Score,Final_Score,Projects_Completed,Overall_Percentage
0,1,18,2,78,8,65,68,70,1,68
1,2,19,3,82,9,70,72,74,2,72
2,3,20,4,85,10,75,78,80,2,78
3,4,18,1,70,6,60,62,65,1,63

In [28]:
df.iloc[1:5,7:10]

   Final_Score  Projects_Completed  Overall_Percentage
1           74                   2                  72
2           80                   2                  78
3           65                   1                  63
4           88                   3                  85

In [32]:
df.iloc[1:5]

,Student_ID,Age,Study_Hours,Attendance_Percent,Assignments_Completed,Quiz_Score,Midterm_Score,Final_Score,Projects_Completed,Overall_Percentage
1,2,19,3,82,9,70,72,74,2,72
2,3,20,4,85,10,75,78,80,2,78
3,4,18,1,70,6,60,62,65,1,63
4,5,21,5,90,10,82,85,88,3,85

In [33]:
df.dtypes

Student_ID               int64
Age                      int64
Study_Hours              int64
Attendance_Percent       int64
Assignments_Completed    int64
Quiz_Score               int64
Midterm_Score            int64
Final_Score              int64
Projects_Completed       int64
Overall_Percentage       int64
dtype: object

In [34]:
df.Projects_Completed.unique()

array([1, 2, 3])

In [35]:
df.loc[:,["Student_ID","Age","Study_Hours" ]]

    Student_ID  Age  Study_Hours
0            1   18            2
1            2   19            3
2            3   20            4
3            4   18            1
4            5   21            5
5            6   19            2
6            7   20            4
7            8   22            6
8            9   18            3
9           10   21            5
10          11   19            2
11          12   20            4
12          13   18            1
13          14   22            6
14          15   21            5
15          16   19            3
16          17   20            4
17          18   18            2
18          19   22            6
19          20   21            5
20          21   19            3
21          22   20            4
22          23   18            2
23          24   22            6